import type { Artist, Artwork, Course, MapLocation, Supply } from "./types";

/**
 * Imágenes reales vendorizadas en /public/img (cargan siempre, rápido, sin
 * depender de hotlink ni rate-limit; same-origin → válidas como texturas WebGL).
 * Origen: Wikimedia Commons (contenido salvadoreño auténtico, licencias libres
 * CC BY / CC BY-SA / CC0 / PD) + Unsplash (retratos/clases). Créditos en CREDITS.md.
 */
export const IMAGES = {
  // Obras
  obraMemoria: "/img/obra-memoria.jpg",
  obraPueblo: "/img/obra-pueblo.jpg",
  obraOccidente: "/img/obra-occidente.jpg",
  obraMuro: "/img/obra-muro.jpg",
  obraAnil: "/img/obra-anil.jpg",
  obraFiesta: "/img/obra-fiesta.jpg",
  obraVolcan: "/img/obra-volcan.jpg",
  obraEsquina: "/img/obra-esquina.jpg",
  // Artistas (retratos)
  artistFernanda: "/img/artist-fernanda.jpg",
  artistTomas: "/img/artist-tomas.jpg",
  artistAna: "/img/artist-ana.jpg",
  artistDiego: "/img/artist-diego.jpg",
  // Cursos
  cursoAcrilico: "/img/curso-acrilico.jpg",
  cursoLaPalma: "/img/curso-lapalma.jpg",
  cursoFoto: "/img/curso-foto.jpg",
  cursoMural: "/img/curso-mural.jpg",
  // Insumos
  insumoAcrilicos: "/img/insumo-acrilicos.jpg",
  insumoLienzo: "/img/insumo-lienzo.jpg",
  insumoPinceles: "/img/insumo-pinceles.jpg",
  insumoCaballete: "/img/insumo-caballete.jpg",
  // Hero + secciones
  hero1: "/img/hero-1.jpg",
  hero2: "/img/hero-2.jpg",
  hero3: "/img/hero-3.jpg",
  seccionHub: "/img/seccion-hub.jpg",
  seccionMapa: "/img/seccion-mapa.jpg",
  seccionAcademy: "/img/seccion-academy.jpg",
} as const;

export const ARTISTS: Artist[] = [
  {
    slug: "fernanda-cuellar",
    name: "Fernanda Cuéllar",
    region: "San Salvador",
    bio: "Pintora contemporánea que explora la memoria urbana de la capital.",
    avatar: IMAGES.artistFernanda,
    featured: true,
  },
  {
    slug: "tomas-mejia",
    name: "Tomás Mejía",
    region: "La Palma, Chalatenango",
    bio: "Heredero del estilo naïf de La Palma fundado por Fernando Llort.",
    avatar: IMAGES.artistTomas,
    featured: true,
  },
  {
    slug: "ana-rivas",
    name: "Ana Rivas",
    region: "Santa Ana",
    bio: "Fotógrafa documental del occidente salvadoreño.",
    avatar: IMAGES.artistAna,
  },
  {
    slug: "diego-portillo",
    name: "Diego Portillo",
    region: "San Miguel",
    bio: "Muralista y artista urbano del oriente del país.",
    avatar: IMAGES.artistDiego,
  },
];

export const ARTWORKS: Artwork[] = [
  {
    id: "1",
    slug: "memoria-de-cuscatlan",
    title: "Memoria de Cuscatlán",
    artistSlug: "fernanda-cuellar",
    artistName: "Fernanda Cuéllar",
    priceCents: 145000,
    type: "physical",
    medium: "Óleo sobre lienzo",
    movement: "Contemporáneo",
    region: "San Salvador",
    year: 2024,
    widthCm: 80,
    heightCm: 100,
    image: IMAGES.obraMemoria,
    description:
      "Una meditación sobre la memoria colectiva de la capital, entre lo que fue y lo que permanece.",
    available: true,
  },
  {
    id: "2",
    slug: "pueblo-de-colores",
    title: "Pueblo de Colores",
    artistSlug: "tomas-mejia",
    artistName: "Tomás Mejía",
    priceCents: 89000,
    type: "physical",
    medium: "Acrílico sobre madera",
    movement: "Naïf / La Palma",
    region: "Chalatenango",
    year: 2023,
    widthCm: 60,
    heightCm: 60,
    image: IMAGES.obraPueblo,
    description:
      "El característico estilo de La Palma: campos, casitas y rostros en geometrías vibrantes.",
    available: true,
  },
  {
    id: "3",
    slug: "occidente-en-blanco-y-negro",
    title: "Occidente en blanco y negro",
    artistSlug: "ana-rivas",
    artistName: "Ana Rivas",
    priceCents: 42000,
    type: "digital",
    medium: "Fotografía / impresión fine-art",
    movement: "Documental",
    region: "Santa Ana",
    year: 2024,
    widthCm: 50,
    heightCm: 70,
    image: IMAGES.obraOccidente,
    description:
      "Serie documental de los mercados y volcanes del occidente salvadoreño.",
    available: true,
  },
  {
    id: "4",
    slug: "muro-vivo",
    title: "Muro Vivo",
    artistSlug: "diego-portillo",
    artistName: "Diego Portillo",
    priceCents: 120000,
    type: "physical",
    medium: "Aerosol y acrílico",
    movement: "Arte urbano",
    region: "San Miguel",
    year: 2025,
    widthCm: 120,
    heightCm: 90,
    image: IMAGES.obraMuro,
    description:
      "Fragmento de mural sobre la identidad migrante del oriente del país.",
    available: true,
  },
  {
    id: "5",
    slug: "raices-de-anil",
    title: "Raíces de Añil",
    artistSlug: "fernanda-cuellar",
    artistName: "Fernanda Cuéllar",
    priceCents: 98000,
    type: "physical",
    medium: "Técnica mixta con añil",
    movement: "Contemporáneo",
    region: "San Salvador",
    year: 2023,
    widthCm: 70,
    heightCm: 90,
    image: IMAGES.obraAnil,
    description: "Homenaje al añil, oro azul de la historia salvadoreña.",
    available: true,
  },
  {
    id: "6",
    slug: "fiesta-patronal",
    title: "Fiesta Patronal",
    artistSlug: "tomas-mejia",
    artistName: "Tomás Mejía",
    priceCents: 76000,
    type: "physical",
    medium: "Acrílico sobre lienzo",
    movement: "Naïf / La Palma",
    region: "Chalatenango",
    year: 2024,
    widthCm: 55,
    heightCm: 75,
    image: IMAGES.obraFiesta,
    description: "El bullicio de una fiesta patronal en clave de color.",
    available: true,
  },
  {
    id: "7",
    slug: "volcan-dormido",
    title: "Volcán Dormido",
    artistSlug: "ana-rivas",
    artistName: "Ana Rivas",
    priceCents: 38000,
    type: "digital",
    medium: "Fotografía / impresión fine-art",
    movement: "Documental",
    region: "Santa Ana",
    year: 2022,
    widthCm: 60,
    heightCm: 40,
    image: IMAGES.obraVolcan,
    description: "El volcán de Santa Ana al amanecer.",
    available: true,
  },
  {
    id: "8",
    slug: "esquina-de-oriente",
    title: "Esquina de Oriente",
    artistSlug: "diego-portillo",
    artistName: "Diego Portillo",
    priceCents: 64000,
    type: "physical",
    medium: "Aerosol sobre metal",
    movement: "Arte urbano",
    region: "San Miguel",
    year: 2025,
    widthCm: 90,
    heightCm: 90,
    image: IMAGES.obraEsquina,
    description: "Retrato urbano de una esquina migueleña.",
    available: false,
  },
];

export const SUPPLIES: Supply[] = [
  {
    id: "s1",
    slug: "set-acrilicos-pro",
    name: "Set de acrílicos profesionales (24)",
    category: "Pinturas",
    priceCents: 4500,
    brand: "Importado",
    image: IMAGES.insumoAcrilicos,
  },
  {
    id: "s2",
    slug: "lienzo-algodon-80x100",
    name: "Lienzo de algodón 80×100 cm",
    category: "Soportes",
    priceCents: 2200,
    brand: "Importado",
    image: IMAGES.insumoLienzo,
  },
  {
    id: "s3",
    slug: "set-pinceles-marta",
    name: "Set de pinceles pelo de marta (12)",
    category: "Pinceles",
    priceCents: 3200,
    brand: "Importado",
    image: IMAGES.insumoPinceles,
  },
  {
    id: "s4",
    slug: "caballete-estudio",
    name: "Caballete de estudio en madera",
    category: "Equipo",
    priceCents: 7800,
    brand: "Importado",
    image: IMAGES.insumoCaballete,
  },
];

export const COURSES: Course[] = [
  {
    slug: "intro-acrilico",
    title: "Introducción al acrílico",
    artistSlug: "fernanda-cuellar",
    artistName: "Fernanda Cuéllar",
    priceCents: 2900,
    level: "Principiante",
    category: "Pintura",
    lessons: 12,
    durationMin: 180,
    cover: IMAGES.cursoAcrilico,
    summary: "Desde cero: materiales, color y tus primeras obras en acrílico.",
  },
  {
    slug: "estilo-la-palma",
    title: "El estilo de La Palma",
    artistSlug: "tomas-mejia",
    artistName: "Tomás Mejía",
    priceCents: 3900,
    level: "Intermedio",
    category: "Pintura",
    lessons: 16,
    durationMin: 240,
    cover: IMAGES.cursoLaPalma,
    summary: "Aprendé el inconfundible estilo naïf salvadoreño paso a paso.",
  },
  {
    slug: "fotografia-documental",
    title: "Fotografía documental salvadoreña",
    artistSlug: "ana-rivas",
    artistName: "Ana Rivas",
    priceCents: 3400,
    level: "Intermedio",
    category: "Fotografía",
    lessons: 10,
    durationMin: 150,
    cover: IMAGES.cursoFoto,
    summary: "Contá historias reales con tu cámara.",
  },
  {
    slug: "mural-urbano",
    title: "Mural urbano de principio a fin",
    artistSlug: "diego-portillo",
    artistName: "Diego Portillo",
    priceCents: 4500,
    level: "Avanzado",
    category: "Arte urbano",
    lessons: 14,
    durationMin: 300,
    cover: IMAGES.cursoMural,
    summary: "Del boceto al muro: técnica, escala y aerosol.",
  },
];

export const LOCATIONS: MapLocation[] = [
  {
    id: "l1",
    name: "Hub SivarArt",
    kind: "hub",
    region: "San Salvador",
    description: "Tienda de insumos + galería incubadora.",
    lat: 13.6989,
    lng: -89.1914,
  },
  {
    id: "l2",
    name: "La Palma — Pueblo artesanal",
    kind: "landmark",
    region: "Chalatenango",
    description: "Cuna del estilo naïf de Fernando Llort.",
    lat: 14.3167,
    lng: -89.1667,
  },
  {
    id: "l3",
    name: "Estudio Cuéllar",
    kind: "studio",
    region: "San Salvador",
    description: "Taller de Fernanda Cuéllar.",
    lat: 13.7,
    lng: -89.2,
  },
  {
    id: "l4",
    name: "Galería Occidente",
    kind: "gallery",
    region: "Santa Ana",
    description: "Espacio de arte en el occidente.",
    lat: 13.9942,
    lng: -89.5597,
  },
  {
    id: "l5",
    name: "Mural de Oriente",
    kind: "landmark",
    region: "San Miguel",
    description: "Mural urbano de Diego Portillo.",
    lat: 13.4833,
    lng: -88.1833,
  },
];

export const getArtwork = (slug: string) =>
  ARTWORKS.find((a) => a.slug === slug);
export const getArtist = (slug: string) =>
  ARTISTS.find((a) => a.slug === slug);
export const getCourse = (slug: string) =>
  COURSES.find((c) => c.slug === slug);
export const artworksByArtist = (slug: string) =>
  ARTWORKS.filter((a) => a.artistSlug === slug);

export const MOVEMENTS = [
  "Contemporáneo",
  "Naïf / La Palma",
  "Documental",
  "Arte urbano",
] as const;
export const REGIONS = [
  "San Salvador",
  "Chalatenango",
  "Santa Ana",
  "San Miguel",
] as const;
